import pandas as pd
import numpy as np
import json

def city():
    try:
        df = pd.read_csv("/home/balaji/Downloads/temp_bq_data/hackathon1_data.csv")
    except Exception as e:
        print("error in reading dataframe",e)
    print("success in reading dataframe")

    lis = []
    dic = dict()

    dic["x"] = json.dumps(df["city_id"].value_counts().index)
    dic["y"] =  json.dumps(df["city_id"].value_counts().values)
    dic["text"] =  json.dumps("City having highest transaction")
    lis.append(dic)

    di = dict()
    dic["x"] = json.dumps(df["city_id"])
    dic["y"] = json.dumps(df["total_cost"])
    dic["text"] = json.dumps("total revenue generated by that city")

    lis.append(dic)

    return lis

